# environment-ci.yml: Additional dependencies to install in the CI environment.
channels:
- conda-forge
- nodefaults
dependencies:
- jupyter
- ipykernel
- make
- matplotlib
- mypy
- netCDF4
- numpydoc
- nodejs
- pandas-stubs
- pooch
- pre-commit
- pytest
- pytest-cov
- tqdm
- zarr=2.18.0
- cartopy
- xgcm
